local CaseProperties = {}

CaseProperties["Items"] = {
	Death = {
		["Elevate"] = 121885146499014,
		["Minecraft"] = 116941381075668
	}, 
	Emotes = {
		["67"] = 79180445676225,
		["LowCortisol"] = 87567280757105,
		["HaiDi"] = 83421797309983,
	}, 
	Count = {
		["Pose3"] = 115818106602857,
		["Yay"] = 113451589990535,
		["PinoyCrouch"] = 108549287750033,
	},
	Images = {
		["t1"] = 8508980536,
		["t2"] = 8508980527
	}
}

-- ["Jojo"] = 103201215781653,  -- Make this premium.

CaseProperties["Chances"] = {
	Death = 50,
	Emotes = 50
}

CaseProperties["CoinPrices"] = {
	NormalCase = 499,
	PremiumCAse = 1299,
	ImageCase = 399
}

CaseProperties["RewardCooldown"] = 43200
CaseProperties["ChestReward"] = 50

return CaseProperties
