local CaseProperties = {}

CaseProperties["Items"] = {
	Death = {
		["Void"] = 00,
	}, 
	Emotes = {
		["Kneel"] = 90964023895915,
		["Crouch"] = 108926550267329,
	}, 
}

CaseProperties["Chances"] = {
	Death = 50,
	Emotes = 50
}

CaseProperties["CoinPrices"] = {
	NormalCase = 500,
	PremiumCAse = 1299
}

CaseProperties["RewardCooldown"] = 43200
CaseProperties["ChestReward"] = 50

return CaseProperties
